
spring:
  application:
    name: dubbo-registry-zookeeper-consumer-sample


dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  config-center:
     address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
demo:
  service:
    version: 1.0.0
