

spring:
  application:
    name: dubbo-registry-nacos-provider-sample


nacos:
  host: 127.0.0.1
  port: 8848

demo:
  service:
    version: 1.0.0


dubbo:
  scan:
    base-packages: com.gzdzss.dubbo.spring.boot.demo.provider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
